apiVersion: v1
kind: Secret
metadata:
  name: wireguard-config
  namespace: wireguard
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    Address = 10.0.0.1/24
    ListenPort = 10.0.0.1/24
    PrivateKey = <server-public-key>

    [Peer]
    PublicKey = <client-public-key>
    AllowedIPs = 10.0.0.2/32
